version: "3"

services:
  db:
    image: postgres
    container_name: auth_extension_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123

  redis:
    image: redis
    container_name: auth_extension_redis
    ports:
      - "6379:6379"
    restart: always
